spring.application.name=Talent Flow
# Conexão com MySQL no Aiven
spring.datasource.url=jdbc:mysql://talentflow-bdd-danmarmel07-df4f.b.aivencloud.com:23967/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_jiWur4gUTREUswCZgth
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


